### ISSUE TITLE
Handle multi-line arrays

### ISSUE THREAD

**Issue by jfilby** [flyx/NimYAML#103] opened 2022-01-02 11:31 UTC
Currently the only way to handle parsing arrays seems to be when they are on a single line, e.g.:

```
- myArray: [ This, is, a, test ]
```
 
This article highlights some alternatives that should parse: https://newbedev.com/yaml-multi-line-arrays

For example:

```
- myArray:
  - This
  - is
  - a
  - test
```

However this doesn't parse successfully with NimYAML.

**Comment by flyx** [comment] 2022-01-02 13:43
This should work. In fact, both inputs yield the exact same output on the [testing ground](https://nimyaml.org/testing.html) as they should. Your problem is likely something else. Have you checked whether you accidentally used tabs for indentation?

If that isn't the problem, try to provide a more complete example with code that works with the first but fails with the second input, and describe the error you get. From what you currently provide, I cannot reproduce any error.

**Comment by flyx** [comment] 2022-06-04 21:16
Closing due to missing feedback, unclear what the error is.

**Closed by flyx** 2022-06-04 21:16 UTC
