### ISSUE TITLE
broken on latest compiler & devel 

### ISSUE THREAD

**Issue by davidnorthetal** [flyx/NimYAML#54] opened 2018-02-01 15:07 UTC
```
0.17.3 [Linux: amd64]
Copyright (c) 2006-2017 by Andreas Rumpf

git hash: fea66497b4f36ed73cfaa5eaa962cfd30307930a
active boot switches: -d:release -d:nativeStackTrace
```

```
libs/yaml/yaml/private/internal.nim(9, 5) Error: expression '
let ii321627 = ("libs/yaml/yaml/serialization.nim", 1060)
echo ["[NimYAML] Error in file ", ii321627.filename, " at line ", ii321627.line, ":"]
echo ["Too many children: " & $recListLen(recCase[i][1])]
echo ["[NimYAML] Stacktrace:"]
try: writeStackTrace()
except: discard
echo ["[NimYAML] Please report this bug."]
quit 1' is of type 'NimNode' and has to be discarded
```

**Comment by dom96** [comment] 2018-02-01 16:22
Looks like this fixes it: https://github.com/flyx/NimYAML/pull/52

**Comment by davidnorthetal** [comment] 2018-02-12 12:27
Does it? - Because it seems that flyx writes that the fix is wrong on a fundemental level and thus of no use?

So it's actually still a pending issue.

**Comment by flyx** [comment] 2018-02-12 13:44
Well the fix makes the error message go away and allows you to compile the code. However, it totally cripples the purpose of `internalError` which is why I won't accept it.

Experience tells me how this issue can be fixed:

 * Open a regression issue with Nim itself.
 * Araq will likely close the issue, stating that *this should never have worked* and hopefully explaining what is wrong with the code.
 * This will give us the necessary information to properly fix this issue.

Frankly, I am tired of hunting down information every time a new Nim version breaks my code. If you are using the development version of Nim, it is *your* responsibility to figure out which changes in the compiler caused the error. I can only address issues with this information. Once the version is released, there are hopefully release notes that help me tracking down the error.

**Comment by davidnorthetal** [comment] 2018-03-05 14:50
> Once the version is released, there are hopefully release notes that help me tracking down the error.

@flyx https://nim-lang.org/blog/2018/03/01/version-0180-released.html does that help?

**Comment by flyx** [comment] 2018-03-14 10:11
I am sorry, I currently have little time dealing with this. Moreover, the release notes do not contain the required information to fix this.

**Closed** 2018-05-29 17:12 UTC
