### ISSUE TITLE
Compile error with Nim 0.17.0

### ISSUE THREAD

**Issue by hohlerde** [flyx/NimYAML#40] opened 2017-05-30 15:27 UTC
With nim 0.17.0 there's a compilation error.

```text
Nim Compiler Version 0.17.0 (2017-05-30) [Linux: amd64]
Copyright (c) 2006-2017 by Andreas Rumpf

git hash: eb83ec2685f5bbd0d65051b1f00502f05a367172
active boot switches: -d:release
```
```text
/home/hohlerde/.nimble/pkgs/yaml-0.9.1/yaml/hints.nim(268, 35) template/generic instantiation from here
/home/hohlerde/.nimble/pkgs/yaml-0.9.1/yaml/hints.nim(112, 3) Error: invalid expression: '
of '~':
  ythInitial => ythNULL'
```
To reproduce just compile the following code:
```nim
import yaml

proc main*() = 
  echo "hello"

when isMainModule:
  main()
```

**Comment by flyx** [comment] 2017-05-30 17:59
Likely a regression in Nim that will be fixed: nim-lang/Nim#5918

**Comment by raydf** [comment] 2017-06-26 21:39
Is there any workaround for this problem?

**Comment by flyx** [comment] 2017-06-27 15:17
Downgrade to Nim 0.16.0.

The code could be fixed, but I am currently busy with other projects, and I hoped this would be a quick fix in the compiler. Since this does not seem to happen, I may shift priorities.

**Comment by raydf** [comment] 2017-06-27 15:37
Thanks @flyx, this is the remaining dependency for moving my project to 0.17.0, but i'll keep an eye on the issue opened and after the fix i'll upgrade.

**Closed** 2017-06-30 14:26 UTC
